### ISSUE TITLE
서비스 관련 엔티티 생성

### ISSUE THREAD

**Issue by D0ri123** [dnd-side-project/dnd-9th-10-backend#1]
## 📌Feature Issue
> 서비스와 관련된 엔티티 클래스를 생성합니다.
## 📝To-do
- [x] Entity 클래스 생성
- [x] Entity간의 관계 매핑
- [x] Entity validation 체크 
## ETC
> [관련 ERD 첨부](https://www.erdcloud.com/d/ouorWDFPfvFnTs9ij)
