### ISSUE TITLE
Friend Domain 헥사고날 아키텍처 리팩토링

### ISSUE THREAD

**Issue by D0ri123** [dnd-side-project/dnd-9th-10-backend#57]
## 📌Feature Issue
> Friend Domain과 관련된 기능을 헥사고날 아키텍처에 기반하여 리팩토링합니다.

## 📝To-do
- [x] 친구 캐릭터 제공
- [x] 친구 등록
- [x] 친구 목록 조회
- [x] 친구 캐릭터 수정 기능 추가
- [x] createdAt, modifiedAt 저장안되는 이슈 
 
## ETC
> Nothing
