### ISSUE TITLE
북마크 등록 기능 구현

### ISSUE THREAD

**Issue by D0ri123** [dnd-side-project/dnd-9th-10-backend#66]
## 📌Feature Issue
> 북마크 등록 기능 구현 

## 📝To-do
- [X] POST, `/api/v1/bookmark`
- [x] #64 toReviewers 부분 반영
- [x] 이전 구조 관련 패키지 삭제
- [X] 친구 점수 반영 로직 구현

## ETC
> Nothing
