### ISSUE TITLE
새로운 도메인 주소 적용

### ISSUE THREAD

**Issue by D0ri123** [dnd-side-project/dnd-9th-10-backend#87]
## 📌Feature Issue
> 배포 환경을 변경하고, 새로운 도메인을 적용합니다. 

## 📝To-do
- [x] github action 파일 수정
- [x] docker 관련 설정 추가
- [x] github action secret 변수 추가
 
## ETC
> Nothing
